apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: aravinth
spec:
  hard:
   requests.cpu: "1"
   requests.memory: 1Gi
   limits.cpu: "2"
   limits.memory: 2Gi
maravinth@k8smaster:~$ cat secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
data:
  db-password: ZGJwYXNzd29yZDEx #dbpassword11
